### ISSUE TITLE
New installation without geofence gives unclear error

### ISSUE THREAD

**Issue by jfberry** [KartulUdus/PoracleJS#261]
`error: Can't seem to handle monster:  Cannot read property 'toLowerCase' of undefined {"stack":"TypeError: Cannot read property 'toLowerCase' of undefined\n    at /root/PoracleJS/src/controllers/controller.js:134:59\n    at Array.map (<anonymous>)\n    at Monster.pointInArea (/root/PoracleJS/src/controllers/controller.js:134:35)\n    at Monster.handle `

What the hell does that mean to anyone anyway? :-)

**Comment by jfberry** [comment]
This is caused by the master branch having a dodgy default geofence.json
Develop has it fixed so on push to master this problem will go away
